- name: Configure Consul cluster
  hosts: consul_instances
  any_errors_fatal: true
  become: true
  become_user: root
  roles:
    - {role: ansible-consul}
  vars:
    ansible_ssh_user: ubuntu
    consul_iface: ens5
    consul_version: 1.5.3
    consul_raw_key: "yw53947wbt"
    consul_dnsmasq_enable: false
    consul_pkg: consul-enterprise_{{consul_version}}+ent_linux_amd64.zip
    consul_checksum_file_url: https://s3-us-west-2.amazonaws.com/hc-enterprise-binaries/consul/ent/{{consul_version}}/consul-enterprise_{{consul_version}}%2Bent_SHA256SUMS
    consul_zip_url: https://s3-us-west-2.amazonaws.com/hc-enterprise-binaries/consul/ent/{{consul_version}}/consul-enterprise_{{consul_version}}%2Bent_linux_amd64.zip

- name: Install Vault
  hosts: vault_instances
  any_errors_fatal: true
  become: true
  become_user: root
  roles:
    - {role: ansible-vault}
  vars:
    ansible_ssh_user: ubuntu
    vault_iface: ens5
    vault_version: 1.2.2
    vault_api_addr: https://10.0.10.13:8200
    vault_pkg: vault-enterprise_{{vault_version}}+ent_linux_amd64.zip
    vault_checksum_file_url: https://s3-us-west-2.amazonaws.com/hc-enterprise-binaries/vault/ent/{{vault_version}}/vault-enterprise_{{vault_version}}%2Bent_SHA256SUMS
    vault_zip_url: https://s3-us-west-2.amazonaws.com/hc-enterprise-binaries/vault/ent/{{vault_version}}/vault-enterprise_{{vault_version}}%2Bent_linux_amd64.zip
    vault_ui: true
    vault_tls_disable: true
    vault_consul: 10.0.10.99:8500
